const HANDLE = require("../handle.js");

var device = new HANDLE.HANDLE(0x264a, 0x232a);
// var device = new HANDLE.HANDLE(0x483, 0x5750);
console.info("device: ", device)
console.info("getDeviceInfo: ", device.getDeviceInfo())
device.write([0x1, 0x2, 0x3, 0x4, 0x5])

console.info(device.write([0x1, 0x2, 0x3, 0x4, 0x5]))
// console.info(device.writeFile('H:/reminder-vue2/node_modules/electron/dist/hbin/hmi_res.hbin', 'hmi_res.hbin', 9));
// console.info(device.writeFile('H:/reminder-vue2/node_modules/electron/dist/hbin/hmi_res.hbin', 'hmi_res.hbin', 9));
// console.info(device.sendWifiInfo('jieshen', 'Jieshen168'));

let data = [
    {
        "obj_id": 8,
        "obj_type": 12,
        "obj_name": "",
        "obj_wifi_name": "jieshen",
        "obj_wifi_pass": "Jieshen168",
        "obj_x": 0,
        "obj_y": 0,
        "obj_w": 100,
        "obj_h": 40,
        "obj_opa": 255,
        "obj_r": 255,
        "obj_g": 255,
        "obj_b": 255,
        "obj_opa_2": 255,
        "obj_r_2": 0,
        "obj_g_2": 0,
        "obj_b_2": 0,
        "obj_opa_3": 255,
        "obj_r_3": 0,
        "obj_g_3": 0,
        "obj_b_3": 0,
        "obj_font_name": "",
        "obj_font_size": 20,
        "obj_font_r": 0,
        "obj_font_g": 0,
        "obj_font_b": 0,
        "obj_val_flag": 0,
        "obj_rise_r": 0,
        "obj_rise_g": 0,
        "obj_rise_b": 0,
        "obj_fall_r": 0,
        "obj_fall_g": 0,
        "obj_fall_b": 0,
        "obj_range_min": 0,
        "obj_range_max": 5,
        "obj_angle_range": 0,
        "obj_rotation": 0,
        "obj_width": 100,
        "obj_progress_interval": 0,
        "obj_point_x_num": 5,
        "obj_point_y_num": 5,
        "obj_time": 3000,
        "obj_var": [
            0
        ],
        "obj_event": 0,
        "obj_action": 0,
        "obj_data": "",
        "obj_reserve": "",
        "obj_url": "",
        "obj_field": "",
        "obj_align_reserve": "",
        "obj_rule_name": [],
        "obj_progress_name": [],
        "obj_is_stock": 0
    },
    {
        "obj_id": 6,
        "obj_type": 2,
        "obj_name": "untitled5",
        "obj_wifi_name": "jieshen",
        "obj_wifi_pass": "Jieshen168",
        "obj_x": 0,
        "obj_y": 0,
        "obj_w": 960,
        "obj_h": 320,
        "obj_opa": 0,
        "obj_r": 0,
        "obj_g": 0,
        "obj_b": 0,
        "obj_opa_2": 0,
        "obj_r_2": 0,
        "obj_g_2": 0,
        "obj_b_2": 0,
        "obj_opa_3": 255,
        "obj_r_3": 0,
        "obj_g_3": 0,
        "obj_b_3": 0,
        "obj_font_name": "",
        "obj_font_size": 20,
        "obj_font_r": 0,
        "obj_font_g": 0,
        "obj_font_b": 0,
        "obj_val_flag": 0,
        "obj_rise_r": 0,
        "obj_rise_g": 0,
        "obj_rise_b": 0,
        "obj_fall_r": 0,
        "obj_fall_g": 0,
        "obj_fall_b": 0,
        "obj_range_min": 0,
        "obj_range_max": 5,
        "obj_angle_range": 0,
        "obj_rotation": 0,
        "obj_width": 960,
        "obj_progress_interval": 0,
        "obj_point_x_num": 5,
        "obj_point_y_num": 5,
        "obj_time": 3000,
        "obj_var": [
            0
        ],
        "obj_event": 0,
        "obj_action": 0,
        "obj_data": "stock.png",
        "obj_reserve": "",
        "obj_url": "",
        "obj_field": "",
        "obj_align_reserve": "",
        "obj_rule_name": [],
        "obj_progress_name": [],
        "obj_is_stock": 0
    },
    {
        "obj_id": 1,
        "obj_type": 1,
        "obj_name": "untitled0",
        "obj_wifi_name": "jieshen",
        "obj_wifi_pass": "Jieshen168",
        "obj_x": 20,
        "obj_y": 80,
        "obj_w": 280,
        "obj_h": 80,
        "obj_opa": 0,
        "obj_r": 0,
        "obj_g": 0,
        "obj_b": 0,
        "obj_opa_2": 0,
        "obj_r_2": 0,
        "obj_g_2": 0,
        "obj_b_2": 0,
        "obj_opa_3": 255,
        "obj_r_3": 0,
        "obj_g_3": 0,
        "obj_b_3": 0,
        "obj_font_name": "",
        "obj_font_size": 50,
        "obj_font_r": 0,
        "obj_font_g": 0,
        "obj_font_b": 0,
        "obj_val_flag": 0,
        "obj_rise_r": 255,
        "obj_rise_g": 0,
        "obj_rise_b": 0,
        "obj_fall_r": 0,
        "obj_fall_g": 255,
        "obj_fall_b": 0,
        "obj_range_min": 0,
        "obj_range_max": 5,
        "obj_angle_range": 0,
        "obj_rotation": 0,
        "obj_width": 280,
        "obj_progress_interval": 0,
        "obj_point_x_num": 5,
        "obj_point_y_num": 5,
        "obj_time": 3000,
        "obj_var": [
            0
        ],
        "obj_event": 4,
        "obj_action": 0,
        "obj_data": "46.050",
        "obj_reserve": "",
        "obj_url": "https://stock-f-reminr-server-aybofoxbug.us-west-1.fcapp.run?BABA",
        "obj_field": "price",
        "obj_align_reserve": "",
        "obj_rule_name": [],
        "obj_progress_name": [],
        "obj_is_stock": 1
    },
    {
        "obj_id": 3,
        "obj_type": 3,
        "obj_name": "untitled2",
        "obj_wifi_name": "jieshen",
        "obj_wifi_pass": "Jieshen168",
        "obj_x": 260,
        "obj_y": 20,
        "obj_w": 720,
        "obj_h": 300,
        "obj_opa": 0,
        "obj_r": 0,
        "obj_g": 0,
        "obj_b": 0,
        "obj_opa_2": 0,
        "obj_r_2": 0,
        "obj_g_2": 0,
        "obj_b_2": 0,
        "obj_opa_3": 255,
        "obj_r_3": 211,
        "obj_g_3": 211,
        "obj_b_3": 211,
        "obj_font_name": "",
        "obj_font_size": 20,
        "obj_font_r": 0,
        "obj_font_g": 0,
        "obj_font_b": 0,
        "obj_val_flag": 0,
        "obj_rise_r": 255,
        "obj_rise_g": 0,
        "obj_rise_b": 0,
        "obj_fall_r": 0,
        "obj_fall_g": 255,
        "obj_fall_b": 0,
        "obj_range_min": 0,
        "obj_range_max": 5,
        "obj_angle_range": 0,
        "obj_rotation": 0,
        "obj_width": 720,
        "obj_progress_interval": 0,
        "obj_point_x_num": 5,
        "obj_point_y_num": 5,
        "obj_time": 3000,
        "obj_var": [
            0
        ],
        "obj_event": 4,
        "obj_action": 0,
        "obj_data": "",
        "obj_reserve": "",
        "obj_url": "https://stock-f-reminr-server-aybofoxbug.us-west-1.fcapp.run?BABA",
        "obj_field": "increase",
        "obj_align_reserve": "",
        "obj_rule_name": [],
        "obj_progress_name": [],
        "obj_is_stock": 1
    }
]

// console.info(device.unpacketFile("H:/reminder-vue2/node_modules/electron/dist/hbin/hmi_res.hbin", "./output"));
// console.info(device.writeFile('H:/reminder-vue2/node_modules/electron/dist/hbin/hmi_res.hbin', 'hmi_res.hbin', 9));
// device.writeFileAsync('H:/reminder-vue2/node_modules/electron/dist/hbin/hmi_res.hbin', 'hmi_res.hbin', 9).then(res => {
//     console.info("res: ", res)
// })

// console.info(device.writeFile('H:/reminder-vue2/node_modules/electron/dist/hbin/hmi_res.hbin', 'hmi_res.hbin', 9));
// console.info(device.writeFile('H:/reminder-vue2/node_modules/electron/dist/hbin/hmi_res.hbin', 'hmi_res.hbin', 9));
