let element2 = [
    {
      obj_id: 5,
      obj_type: 1,
      obj_name: "boottime",
      obj_x: 0,
      obj_y: 110,
      obj_w: 200,
      obj_h: 50,
      obj_opa: 0,
      obj_r: 255,
      obj_g: 0,
      obj_b: 0,
      obj_opa_2: 0,
      obj_r_2: 0,
      obj_g_2: 0,
      obj_b_2: 255,
      obj_font_size: 0,
      obj_font_r: 0,
      obj_font_g: 0,
      obj_font_b: 255,
      obj_range_min: 0,
      obj_range_max: 1000000,
      obj_angle_range: 0,
      obj_rotation: 0,
      obj_width: 0,
      obj_point_x_num: 0,
      obj_point_y_num: 0,
      obj_time: 200,
      obj_var: [],
      obj_event: 3,
      obj_action: 0,
      obj_data: "启动时间",
      obj_reserve: "",
    },
    {
      obj_id: 6,
      obj_type: 1,
      obj_name: "datetime",
      obj_x: 0,
      obj_y: 80,
      obj_w: 200,
      obj_h: 50,
      obj_opa: 0,
      obj_r: 255,
      obj_g: 0,
      obj_b: 0,
      obj_opa_2: 0,
      obj_r_2: 0,
      obj_g_2: 0,
      obj_b_2: 255,
      obj_font_size: 0,
      obj_font_r: 0,
      obj_font_g: 0,
      obj_font_b: 255,
      obj_range_min: 0,
      obj_range_max: 1000000,
      obj_angle_range: 0,
      obj_rotation: 0,
      obj_width: 0,
      obj_point_x_num: 0,
      obj_point_y_num: 0,
      obj_time: 200,
      obj_var: [],
      obj_event: 1,
      obj_action: 0,
      obj_data: "启动时间",
      obj_reserve: "",
    },
    {
      obj_id: 7,
      obj_name: "cpu",
      obj_type: 6,
  
      obj_x: 0,
      obj_y: 150,
      obj_w: 192,
      obj_h: 20,
  
      obj_opa: 255,
      obj_r: 255,
      obj_g: 0,
      obj_b: 0,
  
      obj_opa_2: 255,
      obj_r_2: 0,
      obj_g_2: 0,
      obj_b_2: 255,
  
      obj_font_size: 0,
      obj_font_r: 0,
      obj_font_g: 255,
      obj_font_b: 0,
  
      obj_range_min: 0,
      obj_range_max: 100,
      obj_angle_range: 360,
      obj_rotation: 90,
      obj_width: 20,
  
      obj_point_x_num: 0,
      obj_point_y_num: 0,
  
      obj_time: 1000,
  
      obj_var: [50, 60, 70],
  
      obj_event: 0,
      obj_action: 0,
      obj_data: "CPU",
      obj_reserve: ""
    },
    {
      obj_id: 8,
      obj_name: "network",
      obj_type: 6,
  
      obj_x: 0,
      obj_y: 190,
      obj_w: 192,
      obj_h: 20,
  
      obj_opa: 255,
      obj_r: 255,
      obj_g: 0,
      obj_b: 0,
  
      obj_opa_2: 255,
      obj_r_2: 0,
      obj_g_2: 0,
      obj_b_2: 255,
  
      obj_font_size: 0,
      obj_font_r: 0,
      obj_font_g: 255,
      obj_font_b: 0,
  
      obj_range_min: 0,
      obj_range_max: 100,
      obj_angle_range: 360,
      obj_rotation: 90,
      obj_width: 20,
  
      obj_point_x_num: 0,
      obj_point_y_num: 0,
  
      obj_time: 1000,
  
      obj_var: [50, 60, 70],
  
      obj_event: 0,
      obj_action: 0,
      obj_data: "网络",
      obj_reserve: "",
    },
    {
      obj_id: 9,
      obj_name: "memory",
      obj_type: 6,
  
      obj_x: 0,
      obj_y: 230,
      obj_w: 192,
      obj_h: 20,
  
      obj_opa: 255,
      obj_r: 255,
      obj_g: 0,
      obj_b: 0,
  
      obj_opa_2: 255,
      obj_r_2: 0,
      obj_g_2: 0,
      obj_b_2: 255,
  
      obj_font_size: 0,
      obj_font_r: 0,
      obj_font_g: 255,
      obj_font_b: 0,
  
      obj_range_min: 0,
      obj_range_max: 100,
      obj_angle_range: 360,
      obj_rotation: 90,
      obj_width: 20,
  
      obj_point_x_num: 0,
      obj_point_y_num: 0,
  
      obj_time: 1000,
  
      obj_var: [50, 60, 70],
  
      obj_event: 0,
      obj_action: 0,
      obj_data: "内存",
      obj_reserve: "",
    },
    {
      obj_id: 10,
      obj_name: "disk",
      obj_type: 6,
  
      obj_x: 0,
      obj_y: 270,
      obj_w: 192,
      obj_h: 20,
  
      obj_opa: 255,
      obj_r: 255,
      obj_g: 0,
      obj_b: 0,
  
      obj_opa_2: 255,
      obj_r_2: 0,
      obj_g_2: 0,
      obj_b_2: 255,
  
      obj_font_size: 0,
      obj_font_r: 0,
      obj_font_g: 255,
      obj_font_b: 0,
  
      obj_range_min: 0,
      obj_range_max: 100,
      obj_angle_range: 360,
      obj_rotation: 90,
      obj_width: 20,
  
      obj_point_x_num: 0,
      obj_point_y_num: 0,
  
      obj_time: 1000,
  
      obj_var: [50, 60, 70],
  
      obj_event: 0,
      obj_action: 0,
      obj_data: "磁盘",
      obj_reserve: "",
    },
    {
      obj_id: 11,
      obj_name: "graph1",
      obj_type: 5,
  
      obj_x: 200,
      obj_y: 20,
      obj_w: 280,
      obj_h: 160,
  
      obj_opa: 0,
      obj_r: 0,
      obj_g: 255,
      obj_b: 0,
  
      obj_opa_2: 255,
      obj_r_2: 0,
      obj_g_2: 0,
      obj_b_2: 255,
  
      obj_font_size: 0,
      obj_font_r: 0,
      obj_font_g: 255,
      obj_font_b: 0,
  
      obj_range_min: 0,
      obj_range_max: 100,
      obj_angle_range: 360,
      obj_rotation: 90,
      obj_width: 20,
  
      obj_point_x_num: 1,
      obj_point_y_num: 5,
  
      obj_time: 1000,
  
      obj_var: [10, 30, 70, 80],
  
      obj_event: 0,
      obj_action: 0,
      obj_data: "Bilibili",
      obj_reserve: "",
    },
    {
      obj_id: 12,
      obj_type: 2,
      obj_name: "img1",
      obj_x: 500,
      obj_y: 10,
      obj_w: 320,
      obj_h: 320,
      obj_opa: 0,
      obj_r: 255,
      obj_g: 0,
      obj_b: 0,
      obj_opa_2: 0,
      obj_r_2: 0,
      obj_g_2: 0,
      obj_b_2: 255,
      obj_font_size: 0,
      obj_font_r: 0,
      obj_font_g: 0,
      obj_font_b: 255,
      obj_range_min: 0,
      obj_range_max: 1000000,
      obj_angle_range: 0,
      obj_rotation: 0,
      obj_width: 0,
      obj_point_x_num: 0,
      obj_point_y_num: 0,
      obj_time: 0,
      obj_var: [50, 60, 70],
      obj_event: 0,
      obj_action: 0,
      obj_data: "333.png",
      obj_reserve: "1111.png",
    }
  ]