/*
 * @Author: yaohengfeng 1921934563@qq.com
 * @Date: 2023-01-13 10:53:22
 * @LastEditors: yaohengfeng 1921934563@qq.com
 * @LastEditTime: 2023-03-28 18:19:41
 * @FilePath: \hid-handle\test.js
 * @Description: test.js
 */

const hid = require("./hidhandle.js");
let hidHandle = hid.HidHandle();

const { cpuInfo, memoryInfo, deskInfo } = require("./systemInfo")

console.info("handle: ", hidHandle);

console.info("============================================================");

// 更新buff
// let element = [
//   {
//     obj_action: 0,
//     obj_angle_range: 0,
//     obj_b: 0,
//     obj_b_2: 0,
//     obj_data: "yyy",
//     obj_event: 0,
//     obj_font_b: 0,
//     obj_font_g: 0,
//     obj_font_r: 0,
//     obj_font_size: 18,
//     obj_g: 0,
//     obj_g_2: 0,
//     obj_h: 20,
//     obj_id: 0,
//     obj_name: "name1",
//     obj_opa: 255,
//     obj_opa_2: 255,
//     obj_point_x_num: 5,
//     obj_point_y_num: 5,
//     obj_r: 0,
//     obj_r_2: 0,
//     obj_range_max: 100,
//     obj_range_min: 0,
//     obj_reserve: "",
//     obj_rotation: 0,
//     obj_time: 1000,
//     obj_type: 1,
//     obj_var: [],
//     obj_w: 100,
//     obj_width: 100,
//     obj_x: 1,
//     obj_y: 21,
//   },
//   {
//     obj_action: 0,
//     obj_angle_range: 0,
//     obj_b: 0,
//     obj_b_2: 0,
//     obj_data: "12121211",
//     obj_event: 0,
//     obj_font_b: 224,
//     obj_font_g: 254,
//     obj_font_r: 1,
//     obj_font_size: 18,
//     obj_g: 0,
//     obj_g_2: 0,
//     obj_h: 20,
//     obj_id: 2,
//     obj_name: "untitled2",
//     obj_opa: 255,
//     obj_opa_2: 255,
//     obj_point_x_num: 5,
//     obj_point_y_num: 5,
//     obj_r: 255,
//     obj_r_2: 0,
//     obj_range_max: 100,
//     obj_range_min: 0,
//     obj_reserve: "",
//     obj_rotation: 0,
//     obj_time: 1000,
//     obj_type: 1,
//     obj_var: [],
//     obj_w: 580,
//     obj_width: 580,
//     obj_x: 40,
//     obj_y: 60
//   },
// ];

cpuInfo().then((res) => {
  let element = [
    {
      obj_id: 2,
      obj_type: 1,
      obj_name: "disk",
      obj_x: 0,
      obj_y: 150,
      obj_w: 240,
      obj_h: 20,
      obj_opa: 255,
      obj_r: 206,
      obj_g: 46,
      obj_b: 209,
      obj_opa_2: 255,
      obj_r_2: 0,
      obj_g_2: 0,
      obj_b_2: 0,
      obj_font_size: 18,
      obj_font_r: 215,
      obj_font_g: 228,
      obj_font_b: 27,
      obj_range_min: 0,
      obj_range_max: 100,
      obj_angle_range: 0,
      obj_rotation: 0,
      obj_width: 240,
      obj_point_x_num: 5,
      obj_point_y_num: 5,
      obj_time: 1000,
      obj_var: [0],
      obj_event: 0,
      obj_action: 0,
      obj_data: "磁盘" + deskInfo() + "%",
      obj_reserve: "",
    },
    {
      obj_id: 1,
      obj_type: 1,
      obj_name: "mem",
      obj_x: 0,
      obj_y: 80,
      obj_w: 240,
      obj_h: 20,
      obj_opa: 255,
      obj_r: 214,
      obj_g: 227,
      obj_b: 114,
      obj_opa_2: 255,
      obj_r_2: 0,
      obj_g_2: 0,
      obj_b_2: 0,
      obj_font_size: 18,
      obj_font_r: 0,
      obj_font_g: 42,
      obj_font_b: 255,
      obj_range_min: 0,
      obj_range_max: 100,
      obj_angle_range: 0,
      obj_rotation: 0,
      obj_width: 240,
      obj_point_x_num: 5,
      obj_point_y_num: 5,
      obj_time: 1000,
      obj_var: [0],
      obj_event: 0,
      obj_action: 0,
      obj_data: "内存" + memoryInfo + "%",
      obj_reserve: "",
    },
    {
      obj_id: 0,
      obj_type: 1,
      obj_name: "cpu",
      obj_x: 0,
      obj_y: 0,
      obj_w: 240,
      obj_h: 20,
      obj_opa: 255,
      obj_r: 1,
      obj_g: 249,
      obj_b: 129,
      obj_opa_2: 255,
      obj_r_2: 0,
      obj_g_2: 0,
      obj_b_2: 0,
      obj_font_size: 18,
      obj_font_r: 238,
      obj_font_g: 55,
      obj_font_b: 23,
      obj_range_min: 0,
      obj_range_max: 100,
      obj_angle_range: 0,
      obj_rotation: 0,
      obj_width: 240,
      obj_point_x_num: 5,
      obj_point_y_num: 5,
      obj_time: 1000,
      obj_var: [0],
      obj_event: 0,
      obj_action: 0,
      obj_data: "CPU" + res + "%",
      obj_reserve: "",
    }
  ];

  console.info(hidHandle.hmi_batch_update_screen_data(element));

});

// let element = [
//   {
//     obj_id: 0,
//     obj_type: 1,
//     obj_name: "cpu",
//     obj_x: 0,
//     obj_y: 0,
//     obj_w: 240,
//     obj_h: 20,
//     obj_opa: 255,
//     obj_r: 1,
//     obj_g: 249,
//     obj_b: 129,
//     obj_opa_2: 255,
//     obj_r_2: 0,
//     obj_g_2: 0,
//     obj_b_2: 0,
//     obj_font_size: 18,
//     obj_font_r: 238,
//     obj_font_g: 55,
//     obj_font_b: 23,
//     obj_range_min: 0,
//     obj_range_max: 100,
//     obj_angle_range: 0,
//     obj_rotation: 0,
//     obj_width: 240,
//     obj_point_x_num: 5,
//     obj_point_y_num: 5,
//     obj_time: 1000,
//     obj_var: [90],
//     obj_event: 0,
//     obj_action: 0,
//     obj_data: "CPU 90%",
//     obj_reserve: "",
//   }
// ]

// console.info(hidHandle.hmi_batch_update_screen_data(element));


