/*
 * @Author: yaohengfeng 1921934563@qq.com
 * @Date: 2023-01-13 10:53:22
 * @LastEditors: yaohengfeng 1921934563@qq.com
 * @LastEditTime: 2023-03-27 15:34:12
 * @FilePath: \hid-handle\test.js
 * @Description: test.js
 */

const hid = require("./hidhandle.js");
let hidHandle = hid.HidHandle();

console.info("handle: ", hidHandle);

console.info("============================================================");

// 更新buff
// let element = [
//   {
//     obj_action: 0,
//     obj_angle_range: 0,
//     obj_b: 0,
//     obj_b_2: 0,
//     obj_data: "yyy",
//     obj_event: 0,
//     obj_font_b: 0,
//     obj_font_g: 0,
//     obj_font_r: 0,
//     obj_font_size: 18,
//     obj_g: 0,
//     obj_g_2: 0,
//     obj_h: 20,
//     obj_id: 0,
//     obj_name: "name1",
//     obj_opa: 255,
//     obj_opa_2: 255,
//     obj_point_x_num: 5,
//     obj_point_y_num: 5,
//     obj_r: 0,
//     obj_r_2: 0,
//     obj_range_max: 100,
//     obj_range_min: 0,
//     obj_reserve: "",
//     obj_rotation: 0,
//     obj_time: 1000,
//     obj_type: 1,
//     obj_var: [],
//     obj_w: 100,
//     obj_width: 100,
//     obj_x: 1,
//     obj_y: 21,
//   },
//   {
//     obj_action: 0,
//     obj_angle_range: 0,
//     obj_b: 0,
//     obj_b_2: 0,
//     obj_data: "12121211",
//     obj_event: 0,
//     obj_font_b: 224,
//     obj_font_g: 254,
//     obj_font_r: 1,
//     obj_font_size: 18,
//     obj_g: 0,
//     obj_g_2: 0,
//     obj_h: 20,
//     obj_id: 2,
//     obj_name: "untitled2",
//     obj_opa: 255,
//     obj_opa_2: 255,
//     obj_point_x_num: 5,
//     obj_point_y_num: 5,
//     obj_r: 255,
//     obj_r_2: 0,
//     obj_range_max: 100,
//     obj_range_min: 0,
//     obj_reserve: "",
//     obj_rotation: 0,
//     obj_time: 1000,
//     obj_type: 1,
//     obj_var: [],
//     obj_w: 580,
//     obj_width: 580,
//     obj_x: 40,
//     obj_y: 60
//   },
// ];
let element = [
  {
    obj_action: 0,
    obj_angle_range: 0,
    obj_b: 0,
    obj_b_2: 0,
    obj_data: "yy",
    obj_event: 0,
    obj_font_b: 0,
    obj_font_g: 0,
    obj_font_r: 0,
    obj_font_size: 18,
    obj_g: 0,
    obj_g_2: 0,
    obj_h: 20,
    obj_id: 0,
    obj_name: "kkk",
    obj_opa: 255,
    obj_opa_2: 255,
    obj_point_x_num: 5,
    obj_point_y_num: 5,
    obj_r: 0,
    obj_r_2: 0,
    obj_range_max: 100,
    obj_range_min: 0,
    obj_reserve: "",
    obj_rotation: 0,
    obj_time: 1000,
    obj_type: 1,
    obj_var: [0],
    obj_w: 100,
    obj_width: 100,
    obj_x: 101,
    obj_y: 61,
  },
  {
    obj_action: 0,
    obj_angle_range: 0,
    obj_b: 0,
    obj_b_2: 163,
    obj_data: "net 20 %",
    obj_event: 0,
    obj_font_b: 0,
    obj_font_g: 0,
    obj_font_r: 0,
    obj_font_size: 18,
    obj_g: 0,
    obj_g_2: 223,
    obj_h: 20,
    obj_id: 1,
    obj_name: "net",
    obj_opa: 255,
    obj_opa_2: 255,
    obj_point_x_num: 5,
    obj_point_y_num: 5,
    obj_r: 255,
    obj_r_2: 98,
    obj_range_max: 100,
    obj_range_min: 0,
    obj_reserve: "",
    obj_rotation: 0,
    obj_time: 1000,
    obj_type: 6,
    obj_var: [20],
    obj_w: 240,
    obj_width: 240,
    obj_x: 41,
    obj_y: 21,
  },
  {
    obj_action: 0,
    obj_angle_range: 0,
    obj_b: 0,
    obj_b_2: 211,
    obj_data: "cpu 90 %",
    obj_event: 0,
    obj_font_b: 0,
    obj_font_g: 0,
    obj_font_r: 0,
    obj_font_size: 18,
    obj_g: 0,
    obj_g_2: 111,
    obj_h: 20,
    obj_id: 2,
    obj_name: "cpu",
    obj_opa: 255,
    obj_opa_2: 255,
    obj_point_x_num: 5,
    obj_point_y_num: 5,
    obj_r: 255,
    obj_r_2: 127,
    obj_range_max: 100,
    obj_range_min: 0,
    obj_reserve: "",
    obj_rotation: 0,
    obj_time: 1000,
    obj_type: 6,
    obj_var: [90],
    obj_w: 240,
    obj_width: 240,
    obj_x: 320,
    obj_y: 20
  },
];
console.info(hidHandle.hmi_batch_update_screen_data(element));
