const hid = require("./hidhandle.js");

let data = [
    {
        "obj_id": 8,
        "obj_type": 1,
        "obj_name": "股票",
        "obj_x": 0,
        "obj_y": 0,
        "obj_w": 440,
        "obj_h": 320,
        "obj_opa": 255,
        "obj_r": 250,
        "obj_g": 250,
        "obj_b": 250,
        "obj_opa_2": 255,
        "obj_r_2": 0,
        "obj_g_2": 0,
        "obj_b_2": 0,
        "obj_font_size": 18,
        "obj_font_r": 122,
        "obj_font_g": 245,
        "obj_font_b": 0,
        "obj_range_min": 0,
        "obj_range_max": 100,
        "obj_angle_range": 0,
        "obj_rotation": 0,
        "obj_width": 440,
        "obj_point_x_num": 5,
        "obj_point_y_num": 5,
        "obj_time": 1000,
        "obj_var": [
            0
        ],
        "obj_event": 0,
        "obj_action": 0,
        "obj_data": "",
        "obj_reserve": ""
    },
    {
        "obj_id": 3,
        "obj_type": 1,
        "obj_name": "citys",
        "obj_x": 440,
        "obj_y": 0,
        "obj_w": 520,
        "obj_h": 320,
        "obj_opa": 255,
        "obj_r": 179,
        "obj_g": 255,
        "obj_b": 198,
        "obj_opa_2": 255,
        "obj_r_2": 0,
        "obj_g_2": 0,
        "obj_b_2": 0,
        "obj_font_size": 18,
        "obj_font_r": 255,
        "obj_font_g": 0,
        "obj_font_b": 0,
        "obj_range_min": 0,
        "obj_range_max": 100,
        "obj_angle_range": 0,
        "obj_rotation": 0,
        "obj_width": 520,
        "obj_point_x_num": 5,
        "obj_point_y_num": 5,
        "obj_time": 1000,
        "obj_var": [
            0
        ],
        "obj_event": 0,
        "obj_action": 0,
        "obj_data": "",
        "obj_reserve": ""
    },
    {
        "obj_id": 94783495,
        "obj_type": 1,
        "obj_name": "code",
        "obj_x": 0,
        "obj_y": 20,
        "obj_w": 120,
        "obj_h": 30,
        "obj_opa": 255,
        "obj_r": 196,
        "obj_g": 39,
        "obj_b": 39,
        "obj_opa_2": 255,
        "obj_r_2": 0,
        "obj_g_2": 0,
        "obj_b_2": 0,
        "obj_font_size": 18,
        "obj_font_r": 107,
        "obj_font_g": 245,
        "obj_font_b": 178,
        "obj_range_min": 0,
        "obj_range_max": 100,
        "obj_angle_range": 0,
        "obj_rotation": 0,
        "obj_width": 120,
        "obj_point_x_num": 5,
        "obj_point_y_num": 5,
        "obj_time": 1000,
        "obj_var": [
            0
        ],
        "obj_event": 0,
        "obj_action": 0,
        "obj_data": "BABA",
        "obj_reserve": ""
    },
    {
        "obj_id": 29077505,
        "obj_type": 1,
        "obj_name": "market",
        "obj_x": 320,
        "obj_y": 20,
        "obj_w": 120,
        "obj_h": 30,
        "obj_opa": 255,
        "obj_r": 0,
        "obj_g": 0,
        "obj_b": 0,
        "obj_opa_2": 255,
        "obj_r_2": 0,
        "obj_g_2": 0,
        "obj_b_2": 0,
        "obj_font_size": 18,
        "obj_font_r": 122,
        "obj_font_g": 245,
        "obj_font_b": 0,
        "obj_range_min": 0,
        "obj_range_max": 100,
        "obj_angle_range": 0,
        "obj_rotation": 0,
        "obj_width": 120,
        "obj_point_x_num": 5,
        "obj_point_y_num": 5,
        "obj_time": 1000,
        "obj_var": [
            0
        ],
        "obj_event": 0,
        "obj_action": 0,
        "obj_data": "us",
        "obj_reserve": ""
    },
    {
        "obj_id": 70294559,
        "obj_type": 1,
        "obj_name": "price",
        "obj_x": 180,
        "obj_y": 100,
        "obj_w": 140,
        "obj_h": 30,
        "obj_opa": 255,
        "obj_r": 0,
        "obj_g": 0,
        "obj_b": 0,
        "obj_opa_2": 255,
        "obj_r_2": 0,
        "obj_g_2": 0,
        "obj_b_2": 0,
        "obj_font_size": 18,
        "obj_font_r": 238,
        "obj_font_g": 124,
        "obj_font_b": 124,
        "obj_range_min": 0,
        "obj_range_max": 100,
        "obj_angle_range": 0,
        "obj_rotation": 0,
        "obj_width": 140,
        "obj_point_x_num": 5,
        "obj_point_y_num": 5,
        "obj_time": 1000,
        "obj_var": [
            78.67
        ],
        "obj_event": 0,
        "obj_action": 0,
        "obj_data": "78.670",
        "obj_reserve": ""
    },
    {
        "obj_id": 76133063,
        "obj_type": 1,
        "obj_name": "increase",
        "obj_x": 0,
        "obj_y": 160,
        "obj_w": 320,
        "obj_h": 30,
        "obj_opa": 255,
        "obj_r": 0,
        "obj_g": 240,
        "obj_b": 8,
        "obj_opa_2": 255,
        "obj_r_2": 0,
        "obj_g_2": 0,
        "obj_b_2": 0,
        "obj_font_size": 18,
        "obj_font_r": 0,
        "obj_font_g": 0,
        "obj_font_b": 0,
        "obj_range_min": 0,
        "obj_range_max": 100,
        "obj_angle_range": 0,
        "obj_rotation": 0,
        "obj_width": 320,
        "obj_point_x_num": 5,
        "obj_point_y_num": 5,
        "obj_time": 1000,
        "obj_var": [
            -2.3
        ],
        "obj_event": 0,
        "obj_action": 0,
        "obj_data": "-2.300",
        "obj_reserve": ""
    },
    {
        "obj_id": 61044394,
        "obj_type": 1,
        "obj_name": "ratio",
        "obj_x": 0,
        "obj_y": 100,
        "obj_w": 160,
        "obj_h": 30,
        "obj_opa": 255,
        "obj_r": 249,
        "obj_g": 174,
        "obj_b": 174,
        "obj_opa_2": 255,
        "obj_r_2": 0,
        "obj_g_2": 0,
        "obj_b_2": 0,
        "obj_font_size": 18,
        "obj_font_r": 228,
        "obj_font_g": 251,
        "obj_font_b": 237,
        "obj_range_min": 0,
        "obj_range_max": 100,
        "obj_angle_range": 0,
        "obj_rotation": 0,
        "obj_width": 160,
        "obj_point_x_num": 5,
        "obj_point_y_num": 5,
        "obj_time": 1000,
        "obj_var": [
            0
        ],
        "obj_event": 0,
        "obj_action": 0,
        "obj_data": "-2.84%",
        "obj_reserve": ""
    },
    {
        "obj_id": 72092388,
        "obj_type": 1,
        "obj_name": "name",
        "obj_x": 140,
        "obj_y": 20,
        "obj_w": 140,
        "obj_h": 30,
        "obj_opa": 255,
        "obj_r": 197,
        "obj_g": 177,
        "obj_b": 155,
        "obj_opa_2": 255,
        "obj_r_2": 0,
        "obj_g_2": 0,
        "obj_b_2": 0,
        "obj_font_size": 18,
        "obj_font_r": 240,
        "obj_font_g": 10,
        "obj_font_b": 232,
        "obj_range_min": 0,
        "obj_range_max": 100,
        "obj_angle_range": 0,
        "obj_rotation": 0,
        "obj_width": 140,
        "obj_point_x_num": 5,
        "obj_point_y_num": 5,
        "obj_time": 1000,
        "obj_var": [
            0
        ],
        "obj_event": 0,
        "obj_action": 0,
        "obj_data": "阿里巴巴",
        "obj_reserve": ""
    },
    {
        "obj_id": 87620827,
        "obj_type": 1,
        "obj_name": "query",
        "obj_x": 0,
        "obj_y": 220,
        "obj_w": 220,
        "obj_h": 30,
        "obj_opa": 255,
        "obj_r": 175,
        "obj_g": 187,
        "obj_b": 223,
        "obj_opa_2": 255,
        "obj_r_2": 0,
        "obj_g_2": 0,
        "obj_b_2": 0,
        "obj_font_size": 18,
        "obj_font_r": 230,
        "obj_font_g": 0,
        "obj_font_b": 0,
        "obj_range_min": 0,
        "obj_range_max": 100,
        "obj_angle_range": 0,
        "obj_rotation": 0,
        "obj_width": 220,
        "obj_point_x_num": 5,
        "obj_point_y_num": 5,
        "obj_time": 1000,
        "obj_var": [
            0
        ],
        "obj_event": 0,
        "obj_action": 0,
        "obj_data": "BABA",
        "obj_reserve": ""
    },
    {
        "obj_id": 35233804,
        "obj_type": 1,
        "obj_name": "report",
        "obj_x": 440,
        "obj_y": 0,
        "obj_w": 280,
        "obj_h": 30,
        "obj_opa": 255,
        "obj_r": 0,
        "obj_g": 0,
        "obj_b": 0,
        "obj_opa_2": 255,
        "obj_r_2": 0,
        "obj_g_2": 0,
        "obj_b_2": 0,
        "obj_font_size": 18,
        "obj_font_r": 235,
        "obj_font_g": 0,
        "obj_font_b": 0,
        "obj_range_min": 0,
        "obj_range_max": 100,
        "obj_angle_range": 0,
        "obj_rotation": 0,
        "obj_width": 280,
        "obj_point_x_num": 5,
        "obj_point_y_num": 5,
        "obj_time": 1000,
        "obj_var": [
            0
        ],
        "obj_event": 0,
        "obj_action": 0,
        "obj_data": "2023-05-31 14:06:17",
        "obj_reserve": ""
    },
    {
        "obj_id": 25099135,
        "obj_type": 1,
        "obj_name": "province",
        "obj_x": 440,
        "obj_y": 40,
        "obj_w": 100,
        "obj_h": 30,
        "obj_opa": 255,
        "obj_r": 0,
        "obj_g": 0,
        "obj_b": 0,
        "obj_opa_2": 255,
        "obj_r_2": 0,
        "obj_g_2": 0,
        "obj_b_2": 0,
        "obj_font_size": 18,
        "obj_font_r": 255,
        "obj_font_g": 0,
        "obj_font_b": 0,
        "obj_range_min": 0,
        "obj_range_max": 100,
        "obj_angle_range": 0,
        "obj_rotation": 0,
        "obj_width": 100,
        "obj_point_x_num": 5,
        "obj_point_y_num": 5,
        "obj_time": 1000,
        "obj_var": [
            0
        ],
        "obj_event": 0,
        "obj_action": 0,
        "obj_data": "广西",
        "obj_reserve": ""
    },
    {
        "obj_id": 49697916,
        "obj_type": 1,
        "obj_name": "city",
        "obj_x": 620,
        "obj_y": 40,
        "obj_w": 100,
        "obj_h": 30,
        "obj_opa": 255,
        "obj_r": 0,
        "obj_g": 0,
        "obj_b": 0,
        "obj_opa_2": 255,
        "obj_r_2": 0,
        "obj_g_2": 0,
        "obj_b_2": 0,
        "obj_font_size": 18,
        "obj_font_r": 255,
        "obj_font_g": 0,
        "obj_font_b": 0,
        "obj_range_min": 0,
        "obj_range_max": 100,
        "obj_angle_range": 0,
        "obj_rotation": 0,
        "obj_width": 100,
        "obj_point_x_num": 5,
        "obj_point_y_num": 5,
        "obj_time": 1000,
        "obj_var": [
            0
        ],
        "obj_event": 0,
        "obj_action": 0,
        "obj_data": "北流市",
        "obj_reserve": ""
    },
    {
        "obj_id": 18011427,
        "obj_type": 1,
        "obj_name": "temp",
        "obj_x": 440,
        "obj_y": 100,
        "obj_w": 100,
        "obj_h": 30,
        "obj_opa": 255,
        "obj_r": 0,
        "obj_g": 0,
        "obj_b": 0,
        "obj_opa_2": 255,
        "obj_r_2": 0,
        "obj_g_2": 0,
        "obj_b_2": 0,
        "obj_font_size": 18,
        "obj_font_r": 255,
        "obj_font_g": 0,
        "obj_font_b": 0,
        "obj_range_min": 0,
        "obj_range_max": 100,
        "obj_angle_range": 0,
        "obj_rotation": 0,
        "obj_width": 100,
        "obj_point_x_num": 5,
        "obj_point_y_num": 5,
        "obj_time": 1000,
        "obj_var": [
            0
        ],
        "obj_event": 0,
        "obj_action": 0,
        "obj_data": "36℃",
        "obj_reserve": ""
    },
    {
        "obj_id": 39247968,
        "obj_type": 1,
        "obj_name": "weather",
        "obj_x": 620,
        "obj_y": 100,
        "obj_w": 100,
        "obj_h": 30,
        "obj_opa": 255,
        "obj_r": 0,
        "obj_g": 0,
        "obj_b": 0,
        "obj_opa_2": 255,
        "obj_r_2": 0,
        "obj_g_2": 0,
        "obj_b_2": 0,
        "obj_font_size": 18,
        "obj_font_r": 255,
        "obj_font_g": 0,
        "obj_font_b": 0,
        "obj_range_min": 0,
        "obj_range_max": 100,
        "obj_angle_range": 0,
        "obj_rotation": 0,
        "obj_width": 100,
        "obj_point_x_num": 5,
        "obj_point_y_num": 5,
        "obj_time": 1000,
        "obj_var": [
            0
        ],
        "obj_event": 0,
        "obj_action": 0,
        "obj_data": "晴",
        "obj_reserve": ""
    },
    {
        "obj_id": 52187321,
        "obj_type": 1,
        "obj_name": "humidity",
        "obj_x": 440,
        "obj_y": 160,
        "obj_w": 100,
        "obj_h": 30,
        "obj_opa": 255,
        "obj_r": 0,
        "obj_g": 0,
        "obj_b": 0,
        "obj_opa_2": 255,
        "obj_r_2": 0,
        "obj_g_2": 0,
        "obj_b_2": 0,
        "obj_font_size": 18,
        "obj_font_r": 255,
        "obj_font_g": 0,
        "obj_font_b": 0,
        "obj_range_min": 0,
        "obj_range_max": 100,
        "obj_angle_range": 0,
        "obj_rotation": 0,
        "obj_width": 100,
        "obj_point_x_num": 5,
        "obj_point_y_num": 5,
        "obj_time": 1000,
        "obj_var": [
            54
        ],
        "obj_event": 0,
        "obj_action": 0,
        "obj_data": "54",
        "obj_reserve": ""
    },
    {
        "obj_id": 20833311,
        "obj_type": 1,
        "obj_name": "direction",
        "obj_x": 620,
        "obj_y": 160,
        "obj_w": 100,
        "obj_h": 30,
        "obj_opa": 255,
        "obj_r": 0,
        "obj_g": 0,
        "obj_b": 0,
        "obj_opa_2": 255,
        "obj_r_2": 0,
        "obj_g_2": 0,
        "obj_b_2": 0,
        "obj_font_size": 18,
        "obj_font_r": 255,
        "obj_font_g": 0,
        "obj_font_b": 0,
        "obj_range_min": 0,
        "obj_range_max": 100,
        "obj_angle_range": 0,
        "obj_rotation": 0,
        "obj_width": 100,
        "obj_point_x_num": 5,
        "obj_point_y_num": 5,
        "obj_time": 1000,
        "obj_var": [
            0
        ],
        "obj_event": 0,
        "obj_action": 0,
        "obj_data": "北",
        "obj_reserve": ""
    },
    {
        "obj_id": 1488038,
        "obj_type": 1,
        "obj_name": "windpower",
        "obj_x": 440,
        "obj_y": 220,
        "obj_w": 100,
        "obj_h": 30,
        "obj_opa": 255,
        "obj_r": 0,
        "obj_g": 0,
        "obj_b": 0,
        "obj_opa_2": 255,
        "obj_r_2": 0,
        "obj_g_2": 0,
        "obj_b_2": 0,
        "obj_font_size": 18,
        "obj_font_r": 255,
        "obj_font_g": 0,
        "obj_font_b": 0,
        "obj_range_min": 0,
        "obj_range_max": 100,
        "obj_angle_range": 0,
        "obj_rotation": 0,
        "obj_width": 100,
        "obj_point_x_num": 5,
        "obj_point_y_num": 5,
        "obj_time": 1000,
        "obj_var": [
            0
        ],
        "obj_event": 0,
        "obj_action": 0,
        "obj_data": "≤3",
        "obj_reserve": ""
    }
]

let hidHandle = hid.HidHandle();

console.info("handle: ", hidHandle);

// 默认UI元素
// console.info("HID", hidHandle.hmi_create_obj_test_handle())

// 生成UI文件
hidHandle.generate_ui_handle(data, "./new_ui");
// console.info("更新UI：", hidHandle.hid_write_file_handle('./new_ui/hbin/hmi_res.hbin', 'hmi_res.hbin', 9))
