const hid = require("./hidhandle.js");

let data = [
    {
        "obj_id": 21,
        "obj_type": 1,
        "obj_name": "test",
        "obj_x": 280,
        "obj_y": 40,
        "obj_w": 80,
        "obj_h": 40,
        "obj_opa": 255,
        "obj_r": 81,
        "obj_g": 255,
        "obj_b": 0,
        "obj_opa_2": 255,
        "obj_r_2": 0,
        "obj_g_2": 0,
        "obj_b_2": 0,
        "obj_font_size": 18,
        "obj_font_r": 255,
        "obj_font_g": 0,
        "obj_font_b": 0,
        "obj_range_min": 0,
        "obj_range_max": 100,
        "obj_angle_range": 0,
        "obj_rotation": 0,
        "obj_width": 80,
        "obj_point_x_num": 5,
        "obj_point_y_num": 5,
        "obj_time": 1000,
        "obj_var": [
            0
        ],
        "obj_event": 0,
        "obj_action": 0,
        "obj_data": "提醒器",
        "obj_reserve": ""
    },
    {
        "obj_id": 23,
        "obj_type": 2,
        "obj_name": "img2",
        "obj_x": 740,
        "obj_y": 0,
        "obj_w": 220,
        "obj_h": 200,
        "obj_opa": 255,
        "obj_r": 0,
        "obj_g": 0,
        "obj_b": 0,
        "obj_opa_2": 255,
        "obj_r_2": 0,
        "obj_g_2": 0,
        "obj_b_2": 0,
        "obj_font_size": 0,
        "obj_font_r": 0,
        "obj_font_g": 0,
        "obj_font_b": 0,
        "obj_range_min": 0,
        "obj_range_max": 100,
        "obj_angle_range": 0,
        "obj_rotation": 0,
        "obj_width": 220,
        "obj_point_x_num": 5,
        "obj_point_y_num": 5,
        "obj_time": 1000,
        "obj_var": [
            0
        ],
        "obj_event": 0,
        "obj_action": 0,
        "obj_data": "gg.png",
        "obj_reserve": ""
    },
    {
        "obj_id": 25,
        "obj_type": 1,
        "obj_name": "fan",
        "obj_x": 120,
        "obj_y": 40,
        "obj_w": 120,
        "obj_h": 40,
        "obj_opa": 255,
        "obj_r": 0,
        "obj_g": 0,
        "obj_b": 0,
        "obj_opa_2": 255,
        "obj_r_2": 0,
        "obj_g_2": 0,
        "obj_b_2": 0,
        "obj_font_size": 16,
        "obj_font_r": 255,
        "obj_font_g": 0,
        "obj_font_b": 0,
        "obj_range_min": 0,
        "obj_range_max": 100,
        "obj_angle_range": 0,
        "obj_rotation": 0,
        "obj_width": 120,
        "obj_point_x_num": 5,
        "obj_point_y_num": 5,
        "obj_time": 1000,
        "obj_var": [
            4807196
        ],
        "obj_event": 0,
        "obj_action": 0,
        "obj_data": "4807196",
        "obj_reserve": ""
    },
    {
        "obj_id": 26,
        "obj_type": 1,
        "obj_name": "ftxt",
        "obj_x": 0,
        "obj_y": 40,
        "obj_w": 120,
        "obj_h": 40,
        "obj_opa": 255,
        "obj_r": 0,
        "obj_g": 0,
        "obj_b": 0,
        "obj_opa_2": 255,
        "obj_r_2": 0,
        "obj_g_2": 0,
        "obj_b_2": 0,
        "obj_font_size": 16,
        "obj_font_r": 255,
        "obj_font_g": 0,
        "obj_font_b": 0,
        "obj_range_min": 0,
        "obj_range_max": 100,
        "obj_angle_range": 0,
        "obj_rotation": 0,
        "obj_width": 120,
        "obj_point_x_num": 5,
        "obj_point_y_num": 5,
        "obj_time": 1000,
        "obj_var": [
            0
        ],
        "obj_event": 0,
        "obj_action": 0,
        "obj_data": "粉丝数：",
        "obj_reserve": ""
    },
    {
        "obj_id": 27,
        "obj_type": 1,
        "obj_name": "currency",
        "obj_x": 120,
        "obj_y": 80,
        "obj_w": 120,
        "obj_h": 40,
        "obj_opa": 255,
        "obj_r": 0,
        "obj_g": 0,
        "obj_b": 0,
        "obj_opa_2": 255,
        "obj_r_2": 0,
        "obj_g_2": 0,
        "obj_b_2": 0,
        "obj_font_size": 16,
        "obj_font_r": 0,
        "obj_font_g": 255,
        "obj_font_b": 42,
        "obj_range_min": 0,
        "obj_range_max": 100,
        "obj_angle_range": 0,
        "obj_rotation": 0,
        "obj_width": 120,
        "obj_point_x_num": 5,
        "obj_point_y_num": 5,
        "obj_time": 1000,
        "obj_var": [
            23.267
        ],
        "obj_event": 0,
        "obj_action": 0,
        "obj_data": "23.267",
        "obj_reserve": ""
    },
    {
        "obj_id": 28,
        "obj_type": 1,
        "obj_name": "cu",
        "obj_x": 0,
        "obj_y": 80,
        "obj_w": 120,
        "obj_h": 40,
        "obj_opa": 255,
        "obj_r": 0,
        "obj_g": 0,
        "obj_b": 0,
        "obj_opa_2": 255,
        "obj_r_2": 0,
        "obj_g_2": 0,
        "obj_b_2": 0,
        "obj_font_size": 16,
        "obj_font_r": 81,
        "obj_font_g": 255,
        "obj_font_b": 0,
        "obj_range_min": 0,
        "obj_range_max": 100,
        "obj_angle_range": 0,
        "obj_rotation": 0,
        "obj_width": 120,
        "obj_point_x_num": 5,
        "obj_point_y_num": 5,
        "obj_time": 1000,
        "obj_var": [
            0
        ],
        "obj_event": 0,
        "obj_action": 0,
        "obj_data": "比特币价格",
        "obj_reserve": ""
    },
    {
        "obj_id": 29,
        "obj_type": 1,
        "obj_name": "play",
        "obj_x": 120,
        "obj_y": 120,
        "obj_w": 120,
        "obj_h": 40,
        "obj_opa": 255,
        "obj_r": 0,
        "obj_g": 0,
        "obj_b": 0,
        "obj_opa_2": 255,
        "obj_r_2": 0,
        "obj_g_2": 0,
        "obj_b_2": 0,
        "obj_font_size": 16,
        "obj_font_r": 255,
        "obj_font_g": 0,
        "obj_font_b": 212,
        "obj_range_min": 0,
        "obj_range_max": 100,
        "obj_angle_range": 0,
        "obj_rotation": 0,
        "obj_width": 120,
        "obj_point_x_num": 5,
        "obj_point_y_num": 5,
        "obj_time": 1000,
        "obj_var": [
            320857
        ],
        "obj_event": 0,
        "obj_action": 0,
        "obj_data": "320857",
        "obj_reserve": ""
    },
    {
        "obj_id": 30,
        "obj_type": 1,
        "obj_name": "pp",
        "obj_x": 0,
        "obj_y": 120,
        "obj_w": 120,
        "obj_h": 40,
        "obj_opa": 255,
        "obj_r": 0,
        "obj_g": 0,
        "obj_b": 0,
        "obj_opa_2": 255,
        "obj_r_2": 0,
        "obj_g_2": 0,
        "obj_b_2": 0,
        "obj_font_size": 16,
        "obj_font_r": 251,
        "obj_font_g": 0,
        "obj_font_b": 255,
        "obj_range_min": 0,
        "obj_range_max": 100,
        "obj_angle_range": 0,
        "obj_rotation": 0,
        "obj_width": 120,
        "obj_point_x_num": 5,
        "obj_point_y_num": 5,
        "obj_time": 1000,
        "obj_var": [
            0
        ],
        "obj_event": 0,
        "obj_action": 0,
        "obj_data": "Youtbu播放量",
        "obj_reserve": ""
    },
    {
        "obj_id": 8,
        "obj_type": 1,
        "obj_name": "gogo",
        "obj_x": 120,
        "obj_y": 160,
        "obj_w": 120,
        "obj_h": 30,
        "obj_opa": 255,
        "obj_r": 0,
        "obj_g": 0,
        "obj_b": 0,
        "obj_opa_2": 255,
        "obj_r_2": 0,
        "obj_g_2": 0,
        "obj_b_2": 0,
        "obj_font_size": 18,
        "obj_font_r": 255,
        "obj_font_g": 0,
        "obj_font_b": 0,
        "obj_range_min": 0,
        "obj_range_max": 100,
        "obj_angle_range": 0,
        "obj_rotation": 0,
        "obj_width": 120,
        "obj_point_x_num": 5,
        "obj_point_y_num": 5,
        "obj_time": 1000,
        "obj_var": [
            5000
        ],
        "obj_event": 0,
        "obj_action": 0,
        "obj_data": "5000",
        "obj_reserve": ""
    },
    {
        "obj_id": 9,
        "obj_type": 1,
        "obj_name": "cou",
        "obj_x": 0,
        "obj_y": 160,
        "obj_w": 120,
        "obj_h": 30,
        "obj_opa": 255,
        "obj_r": 0,
        "obj_g": 0,
        "obj_b": 0,
        "obj_opa_2": 255,
        "obj_r_2": 0,
        "obj_g_2": 0,
        "obj_b_2": 0,
        "obj_font_size": 16,
        "obj_font_r": 0,
        "obj_font_g": 191,
        "obj_font_b": 255,
        "obj_range_min": 0,
        "obj_range_max": 100,
        "obj_angle_range": 0,
        "obj_rotation": 0,
        "obj_width": 120,
        "obj_point_x_num": 5,
        "obj_point_y_num": 5,
        "obj_time": 1000,
        "obj_var": [
            0
        ],
        "obj_event": 0,
        "obj_action": 0,
        "obj_data": "众筹金额",
        "obj_reserve": ""
    }
]

let hidHandle = hid.HidHandle();

console.info("handle: ", hidHandle);

// 默认UI元素
// console.info("HID", hidHandle.hmi_create_obj_test_handle())

// 生成UI文件
hidHandle.generate_ui_handle(data, "./new_ui");
console.info("更新UI：", hidHandle.hid_write_file_handle('./new_ui/hbin/hmi_res.hbin', 'hmi_res.hbin', 9))
