/*
 * @Author: yaohengfeng 1921934563@qq.com
 * @Date: 2023-01-13 10:53:22
 * @LastEditors: 姚恒锋 1921934563@qq.com
 * @LastEditTime: 2023-07-07 17:17:04
 * @FilePath: \hid-handle\test.js
 * @Description: test.js
 */

const hid = require("./hidhandle.js");
let hidHandle = hid.HidHandle();

console.info("handle: ", hidHandle);

// let data = [
//   {
//     obj_id: 0,
//     obj_type: 1,
//     obj_name: "label0",
//     obj_x: 0,
//     obj_y: 0,
//     obj_w: 100,
//     obj_h: 20,
//     obj_opa: 255,
//     obj_r: 255,
//     obj_g: 12,
//     obj_b: 12,
//     obj_opa_2: 0,
//     obj_r_2: 0,
//     obj_g_2: 0,
//     obj_b_2: 0,
//     obj_font_size: 0,
//     obj_font_r: 0,
//     obj_font_g: 0,
//     obj_font_b: 0,
//     obj_range_min: 0,
//     obj_range_max: 1000000,
//     obj_angle_range: 0,
//     obj_rotation: 0,
//     obj_width: 0,
//     obj_point_x_num: 0,
//     obj_point_y_num: 0,
//     obj_time: 0,
//     obj_var: [],
//     obj_event: 0,
//     obj_action: 0,
//     obj_data: "label0",
//     obj_reserve: "",
//   },
//   {
//     obj_id: 1,
//     obj_type: 1,
//     obj_name: "label1",
//     obj_x: 100,
//     obj_y: 0,
//     obj_w: 100,
//     obj_h: 20,
//     obj_opa: 255,
//     obj_r: 255,
//     obj_g: 12,
//     obj_b: 12,
//     obj_opa_2: 0,
//     obj_r_2: 0,
//     obj_g_2: 0,
//     obj_b_2: 0,
//     obj_font_size: 0,
//     obj_font_r: 0,
//     obj_font_g: 0,
//     obj_font_b: 0,
//     obj_range_min: 0,
//     obj_range_max: 1000000,
//     obj_angle_range: 0,
//     obj_rotation: 0,
//     obj_width: 0,
//     obj_point_x_num: 0,
//     obj_point_y_num: 0,
//     obj_time: 0,
//     obj_var: [],
//     obj_event: 0,
//     obj_action: 0,
//     obj_data: "label1",
//     obj_reserve: "",
//   },
//   {
//     obj_id: 2,
//     obj_type: 1,
//     obj_name: "label2",
//     obj_x: 200,
//     obj_y: 0,
//     obj_w: 100,
//     obj_h: 20,
//     obj_opa: 255,
//     obj_r: 255,
//     obj_g: 12,
//     obj_b: 12,
//     obj_opa_2: 0,
//     obj_r_2: 0,
//     obj_g_2: 0,
//     obj_b_2: 0,
//     obj_font_size: 0,
//     obj_font_r: 0,
//     obj_font_g: 0,
//     obj_font_b: 0,
//     obj_range_min: 0,
//     obj_range_max: 1000000,
//     obj_angle_range: 0,
//     obj_rotation: 0,
//     obj_width: 0,
//     obj_point_x_num: 0,
//     obj_point_y_num: 0,
//     obj_time: 0,
//     obj_var: [],
//     obj_event: 0,
//     obj_action: 0,
//     obj_data: "label2",
//     obj_reserve: "",
//   },
//   {
//     obj_id: 3,
//     obj_type: 1,
//     obj_name: "label3",
//     obj_x: 300,
//     obj_y: 0,
//     obj_w: 100,
//     obj_h: 20,
//     obj_opa: 255,
//     obj_r: 255,
//     obj_g: 12,
//     obj_b: 12,
//     obj_opa_2: 0,
//     obj_r_2: 0,
//     obj_g_2: 0,
//     obj_b_2: 0,
//     obj_font_size: 0,
//     obj_font_r: 0,
//     obj_font_g: 0,
//     obj_font_b: 0,
//     obj_range_min: 0,
//     obj_range_max: 1000000,
//     obj_angle_range: 0,
//     obj_rotation: 0,
//     obj_width: 0,
//     obj_point_x_num: 0,
//     obj_point_y_num: 0,
//     obj_time: 0,
//     obj_var: [],
//     obj_event: 0,
//     obj_action: 0,
//     obj_data: "label3",
//     obj_reserve: "",
//   },
//   {
//     obj_id: 4,
//     obj_type: 1,
//     obj_name: "label4",
//     obj_x: 400,
//     obj_y: 0,
//     obj_w: 100,
//     obj_h: 20,
//     obj_opa: 255,
//     obj_r: 255,
//     obj_g: 12,
//     obj_b: 12,
//     obj_opa_2: 0,
//     obj_r_2: 0,
//     obj_g_2: 0,
//     obj_b_2: 0,
//     obj_font_size: 0,
//     obj_font_r: 0,
//     obj_font_g: 0,
//     obj_font_b: 0,
//     obj_range_min: 0,
//     obj_range_max: 1000000,
//     obj_angle_range: 0,
//     obj_rotation: 0,
//     obj_width: 0,
//     obj_point_x_num: 0,
//     obj_point_y_num: 0,
//     obj_time: 0,
//     obj_var: [],
//     obj_event: 0,
//     obj_action: 0,
//     obj_data: "label4",
//     obj_reserve: "",
//   },
//   {
//     obj_id: 5,
//     obj_type: 1,
//     obj_name: "label5",
//     obj_x: 500,
//     obj_y: 0,
//     obj_w: 100,
//     obj_h: 20,
//     obj_opa: 255,
//     obj_r: 255,
//     obj_g: 12,
//     obj_b: 12,
//     obj_opa_2: 0,
//     obj_r_2: 0,
//     obj_g_2: 0,
//     obj_b_2: 0,
//     obj_font_size: 0,
//     obj_font_r: 0,
//     obj_font_g: 0,
//     obj_font_b: 0,
//     obj_range_min: 0,
//     obj_range_max: 1000000,
//     obj_angle_range: 0,
//     obj_rotation: 0,
//     obj_width: 0,
//     obj_point_x_num: 0,
//     obj_point_y_num: 0,
//     obj_time: 0,
//     obj_var: [],
//     obj_event: 0,
//     obj_action: 0,
//     obj_data: "label5",
//     obj_reserve: "",
//   },
//   {
//     obj_id: 6,
//     obj_type: 1,
//     obj_name: "label6",
//     obj_x: 600,
//     obj_y: 0,
//     obj_w: 100,
//     obj_h: 20,
//     obj_opa: 255,
//     obj_r: 255,
//     obj_g: 12,
//     obj_b: 12,
//     obj_opa_2: 0,
//     obj_r_2: 0,
//     obj_g_2: 0,
//     obj_b_2: 0,
//     obj_font_size: 0,
//     obj_font_r: 0,
//     obj_font_g: 0,
//     obj_font_b: 0,
//     obj_range_min: 0,
//     obj_range_max: 1000000,
//     obj_angle_range: 0,
//     obj_rotation: 0,
//     obj_width: 0,
//     obj_point_x_num: 0,
//     obj_point_y_num: 0,
//     obj_time: 0,
//     obj_var: [],
//     obj_event: 0,
//     obj_action: 0,
//     obj_data: "label6",
//     obj_reserve: "",
//   },
//   {
//     obj_id: 7,
//     obj_name: "cpu",
//     obj_type: 6,

//     obj_x: 0,
//     obj_y: 150,
//     obj_w: 192,
//     obj_h: 20,

//     obj_opa: 255,
//     obj_r: 255,
//     obj_g: 0,
//     obj_b: 0,

//     obj_opa_2: 255,
//     obj_r_2: 0,
//     obj_g_2: 0,
//     obj_b_2: 255,

//     obj_font_size: 0,
//     obj_font_r: 0,
//     obj_font_g: 255,
//     obj_font_b: 0,

//     obj_range_min: 0,
//     obj_range_max: 100,
//     obj_angle_range: 360,
//     obj_rotation: 90,
//     obj_width: 20,

//     obj_point_x_num: 0,
//     obj_point_y_num: 0,

//     obj_time: 1000,

//     obj_var: [50, 60, 70],

//     obj_event: 0,
//     obj_action: 0,
//     obj_data: "CPU",
//     obj_reserve: ""
//   },
//   {
//     obj_id: 8,
//     obj_name: "network",
//     obj_type: 6,

//     obj_x: 0,
//     obj_y: 190,
//     obj_w: 192,
//     obj_h: 20,

//     obj_opa: 255,
//     obj_r: 255,
//     obj_g: 0,
//     obj_b: 0,

//     obj_opa_2: 255,
//     obj_r_2: 0,
//     obj_g_2: 0,
//     obj_b_2: 255,

//     obj_font_size: 0,
//     obj_font_r: 0,
//     obj_font_g: 255,
//     obj_font_b: 0,

//     obj_range_min: 0,
//     obj_range_max: 100,
//     obj_angle_range: 360,
//     obj_rotation: 90,
//     obj_width: 20,

//     obj_point_x_num: 0,
//     obj_point_y_num: 0,

//     obj_time: 1000,

//     obj_var: [50, 60, 70],

//     obj_event: 0,
//     obj_action: 0,
//     obj_data: "network",
//     obj_reserve: "",
//   },
//   {
//     obj_id: 9,
//     obj_name: "memory",
//     obj_type: 6,

//     obj_x: 0,
//     obj_y: 230,
//     obj_w: 192,
//     obj_h: 20,

//     obj_opa: 255,
//     obj_r: 255,
//     obj_g: 0,
//     obj_b: 0,

//     obj_opa_2: 255,
//     obj_r_2: 0,
//     obj_g_2: 0,
//     obj_b_2: 255,

//     obj_font_size: 0,
//     obj_font_r: 0,
//     obj_font_g: 255,
//     obj_font_b: 0,

//     obj_range_min: 0,
//     obj_range_max: 100,
//     obj_angle_range: 360,
//     obj_rotation: 90,
//     obj_width: 20,

//     obj_point_x_num: 0,
//     obj_point_y_num: 0,

//     obj_time: 1000,

//     obj_var: [50, 60, 70],

//     obj_event: 0,
//     obj_action: 0,
//     obj_data: "memory",
//     obj_reserve: "",
//   },
//   {
//     obj_id: 10,
//     obj_name: "disk",
//     obj_type: 6,

//     obj_x: 0,
//     obj_y: 270,
//     obj_w: 192,
//     obj_h: 20,

//     obj_opa: 255,
//     obj_r: 255,
//     obj_g: 0,
//     obj_b: 0,

//     obj_opa_2: 255,
//     obj_r_2: 0,
//     obj_g_2: 0,
//     obj_b_2: 255,

//     obj_font_size: 0,
//     obj_font_r: 0,
//     obj_font_g: 255,
//     obj_font_b: 0,

//     obj_range_min: 0,
//     obj_range_max: 100,
//     obj_angle_range: 360,
//     obj_rotation: 90,
//     obj_width: 20,

//     obj_point_x_num: 0,
//     obj_point_y_num: 0,

//     obj_time: 1000,

//     obj_var: [50, 60, 70],

//     obj_event: 0,
//     obj_action: 0,
//     obj_data: "disk",
//     obj_reserve: "",
//   },
// ];

console.info("============================================================");

// 设置WIFI
// console.info("设置WIFI：")
// console.info(hidHandle.hmi_send_wifi_info_handle("jieshen", "Jieshen168"))

// 生成UI
console.info(hidHandle.test_handle())

// 写入文件更新UI
// console.info(
//   hidHandle.hid_write_file_handle("./ui/hmi_res.hbin", "hmi_res.hbin", 1)
// )

// 更新数据
// console.info("更新数据：");
// console.info(hidHandle.hmi_page_update_elem_var_handle());
